### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by emepetres** [cloudify-cosmo/cloudify-rest-client#203]
I'm trying to run the example with cloudify-rest-client==4.1 against my manager (community ed) with the lines:

client = CloudifyClient('http://[ip]', username='admin', password='[pass]', tenant='default_tenant')
blueprints = client.blueprints.list()

The second line gives me the following error:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    blueprints = client.blueprints.list()
  File "/usr/local/lib/python2.7/dist-packages/cloudify_rest_client/blueprints.py", line 132, in list
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/cloudify_rest_client/client.py", line 239, in get
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/cloudify_rest_client/client.py", line 221, in do_request
    verify=self.get_request_verify(), timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/cloudify_rest_client/client.py", line 143, in _do_request
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //10.38.3.74:80/api/3.1/blueprints (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88c7a4ad50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

I've tested that the client machine has connection to the manager ip on port 80.

**Comment by geokala** [comment]
Hi @emepetres 
Does `cfy status` for cloudify==4.1 work for you against that manager?

If so, what is the output of `cfy --version`?

**Comment by tehasdf** [comment]
Please note the first argument is just `host`, and the "http" part should have been passed as a separate `protocol` argument, eg:
```python
CloudifyClient(host='[ip]', username='admin', protocol='https')  # http is the default, which you don't need to pass
```

**Comment by emepetres** [comment]
@tehasdf removing protocol from host argument did the trick, thanks.

However docs should be modified as it is stated as example:
`client = CloudifyClient('http://MANAGER_HOST')`
which I understand is wrong.

**Comment by isaac-s** [comment]
@emepetres thank you, I submitted a PR to update the docs. https://github.com/cloudify-cosmo/cloudify-rest-client/pull/204
